# Generated by Django 4.0.2 on 2022-07-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_tweet_sentiment_alter_tweet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='sentiments',
            field=models.CharField(default='Some String', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.CharField(max_length=100, primary_key=b'I01\n', serialize=False),
        ),
    ]
